In [82]:
import numpy as np

1. Write a NumPy program to convert a list of numeric value into a one-dimensional NumPy array.

Expected Output:
Original List: [12.23, 13.32, 100, 36.32]

One-dimensional NumPy array: [ 12.23 13.32 100. 36.32]



![python-numpy-image-exercise-2.png](attachment:python-numpy-image-exercise-2.png)

In [83]:
#comma will add what's to follow
l = [12.23, 13.32, 100, 36.32]
print("Original List:",l)
a = np.array(l)
print("One-dimensional NumPy array: ",a)

Original List: [12.23, 13.32, 100, 36.32]
One-dimensional NumPy array:  [ 12.23  13.32 100.    36.32]


2. Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10. 

Expected Output:

[[ 2 3 4]
[ 5 6 7]
[ 8 9 10]]

![python-numpy-image-exercise-3.png](attachment:python-numpy-image-exercise-3.png)

In [56]:
#create an array of # from 2-10 is .arrange
#can make it equal to x then print 

np.arange(2,11).reshape([3,3])

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

 3. Write a NumPy program to create a null vector of size 10 and update sixth value to 11.
 
[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

Update sixth value to 11

[ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]

![python-numpy-image-exercise-4.png](attachment:python-numpy-image-exercise-4.png)

In [85]:
zeroarray =np.zeros(10)
print(zeroarray)
zeroarray[6]=11
print(zeroarray)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


4. Write a NumPy program to create an array with values ranging from 12 to 38.

Expected Output:

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]

![python-numpy-image-exercise-5.png](attachment:python-numpy-image-exercise-5.png)

In [58]:
#not sure the discrepance with the instruction
#and expected output

np.arange(12,39)

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37, 38])

5. Write a NumPy program to reverse an array (first element becomes last). 

Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]

Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]

![python-numpy-image-exercise-6.png](attachment:python-numpy-image-exercise-6.png)

In [86]:
orig_array=np.arange(12,38)
revarray=orig_array[::-1] #start, stop, 2 is steps, rvs -1
print(orig_array)
print(revarray)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


6. Write a NumPy program to convert an array to a float type.

Sample output:

Original array
[1, 2, 3, 4]

Array converted to a float type:
[ 1. 2. 3. 4.]

![python-numpy-image-exercise-7.png](attachment:python-numpy-image-exercise-7.png)

In [63]:
#float means includes decimals

a=[1, 2, 3, 4]
intarray=np.array(a)
print(intarray)
floatarray = np.asfarray(intarray)
print(floatarray)

[1 2 3 4]
[1. 2. 3. 4.]


7. Write a NumPy program to create a 2d array with 1 on the border and 0 inside. 

Expected Output:

Original array:
[[ 1. 1. 1. 1. 1.]

...................

[ 1. 1. 1. 1. 1.]]

1 on the border and 0 inside in the array

[[ 1. 1. 1. 1. 1.]]

...................

[ 1. 1. 1. 1. 1.]]

![python-numpy-image-exercise-8.png](attachment:python-numpy-image-exercise-8.png)

In [91]:
#creat an array of all ones
#start from second row to second from last 1,-1

x = np.ones((5,5))
print("Original array:")
print(x)
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)


Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


8. Write a NumPy program to add a border (filled with 0's) around an existing array. 

Expected Output:

Original array:

[[ 1. 1. 1.]

[ 1. 1. 1.]

[ 1. 1. 1.]]

1 on the border and 0 inside in the array

[[ 0. 0. 0. 0. 0.]

...........

[ 0. 0. 0. 0. 0.]]

![python-numpy-image-exercise-9.png](attachment:python-numpy-image-exercise-9.png)

In [92]:
x = np.ones((3,3)) #determines dimensionality
print("Original array:")
print(x)
print("0 on the border and 1 inside in the array")
x = np.pad(x, pad_width=1, mode='constant', constant_values=0) #padding useful in deep learning
print(x)

Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


9. Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern. 

Checkerboard pattern:

[[0 1 0 1 0 1 0 1]

..........

[0 1 0 1 0 1 0 1]

[1 0 1 0 1 0 1 0]]

In [96]:
x = np.ones((3,3)) #don't understand the reasoning for this line of code
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


10. Write a NumPy program to convert a list and tuple into arrays. 

List to array:

[1 2 3 4 5 6 7 8]

Tuple to array:

[[8 4 6]
[1 2 3]]

![python-numpy-image-exercise-11.png](attachment:python-numpy-image-exercise-11.png)

In [97]:
my_list = [1, 2, 3, 4, 5, 6, 7, 8]
print("List to array: ")
print(np.asarray(my_list))
my_tuple = ([8, 4, 6], [1, 2, 3]) #2-tuple
print("Tuple to array: ")
print(np.asarray(my_tuple))

List to array: 
[1 2 3 4 5 6 7 8]
Tuple to array: 
[[8 4 6]
 [1 2 3]]


11. Write a NumPy program to append values to the end of an array.

Expected Output:

Original array:
[10, 20, 30]

After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]

![python-numpy-image-exercise-12.png](attachment:python-numpy-image-exercise-12.png)

In [2]:
#Adding values at the end of the array
#data is not fixed and is prone to change.
#we can use numpy.append(). 
#This function appends a single value & multiple values 
#Adds at the end of the array.
#Syntax : numpy.append(array, values, axis = None)
#Parameters :
#array : Input array.
#values : values to be added in the array.
#axis : Axis along which we want to insert the values.
#Returns : An copy of array with values being appended at the end
#along a given axis.

import numpy as np

In [12]:
#Establish original array
#brackets inside the parenthesis

x=np.array([10,20,30])
x

array([10, 20, 30])

In [41]:
#append the array
#I didn't get back the 2 dimensions?

appended_array=np.append(x,[[40,50,60],[70,80,90]])
print(appended_array)
print(appended_array.ndim)

[ 1.  2.  3. 40. 50. 60. 70. 80. 90.]
1


12. Write a NumPy program to convert the values of Centigrade degrees into Fahrenheit degrees. Centigrade values are stored into a NumPy array.

Sample Array [0, 12, 45.21 ,34, 99.91]

Values in Fahrenheit degrees:                                           
[  0.    12.    45.21  34.    99.91]                                    
Values in  Centigrade degrees:                                          
[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]

![python-numpy-image-exercise-14.png](attachment:python-numpy-image-exercise-14.png)

In [36]:
#Creating a conversion calculation
#any variable with letters need to be defined
#equation provided for C did not work???
#use np.round to 2 decimals


import numpy as np
f_values = [0, 12, 45.21, 34, 99.91]
f=np.array(f_values)
print("Fahrenheit converted to Celsius:")
print(np.round((5*f/9 - 5*32/9),2))

These are the Celsius values
[-17.78 -11.11   7.34   1.11  37.73]


In [39]:
c_values = [-17.77777778, -11.11111111, 7.33888889, 1.11111111, 37.72777778]
C=np.array(c_values)
print('Celcius converted to Fahrenheit:')
print(np.round((9*C+(32*5))/5,2))

Celcius converted to Fahrenheit:
[-0.   12.   45.21 34.   99.91]


13. Write a NumPy program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements

![python-numpy-image-exercise-16.png](attachment:python-numpy-image-exercise-16.png)

In [40]:
#x.size gives you # of elements of a given axis
#memory numpy arrays take up = dtype, itemsize
#itemsize is length of 1 array in bytes, 32 is default = 4
#nbytes=.size*.itemsize
#The float () method takes a single parameter: 
#x - number or string that needs to be converted to floating point #
#Floating point # = real # or # contains a fractional part
#dtype=np.float(64) taken from numpy API reference


x = np.array([1,2,3], dtype=np.float64)
print("Size of the array: ", x.size)
print("Length of one array element in bytes: ", x.itemsize)
print("Total bytes consumed by the elements of the array: ", x.nbytes)

Size of the array:  3
Length of one array element in bytes:  8
Total bytes consumed by the elements of the array:  24


14. Write a NumPy program to find common values between two arrays.

Array1:  [ 0 10 20 40 60]                                              
Array2:  [10, 30, 40]                                                  
Common values between two arrays:                                      
[10 40]

![python-numpy-image-exercise-18.png](attachment:python-numpy-image-exercise-18.png)

In [42]:
#use.intersect1d to get common values of 2 1D arrays
#how to increase tuple or dimensions?

array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


15. Write a NumPy program to get the unique elements of an array. 

Expected Output:
Original array:
[10 10 20 20 30 30]
Unique elements of the above array:
[10 20 30]
Original array:
[[1 1]
[2 3]]
Unique elements of the above array:
[1 2 3]

![python-numpy-image-exercise-19.png](attachment:python-numpy-image-exercise-19.png)

In [48]:
#numpy.unique function
#start w/ original array and create x w/ numpy array
#create string that preceeds x
#create string preceeds x above the array
#use np.unique here
#you can define x twice???

x = np.array([10, 10, 20, 20, 30, 30])
print("Original array:")
print(x)
print("Unique elements of the above array:")
print(np.unique(x))
x = np.array([[1, 1], [2, 3]])
print("Original array:")
print(x)
print("Unique elements of the above array:")
print(np.unique(x))

Original array:
[10 10 20 20 30 30]
Unique elements of the above array:
[10 20 30]
Original array:
[[1 1]
 [2 3]]
Unique elements of the above array:
[1 2 3]


16. Write a NumPy program to find the set difference of two arrays. The set difference will return the sorted, unique values in array1 that are not in array2.

Array1:  [ 0 10 20 40 60 80]                                           
Array2:  [10, 30, 40, 50, 70]                                          
Unique values in array1 that are not in array2:                        
[ 0 20 60 80]

![python-numpy-image-exercise-20.png](attachment:python-numpy-image-exercise-20.png)

In [51]:
#The numpy setdiff1d() function is used to find the set difference of two arrays. 
#The following is the syntax:
#diff = np.setdiff1d(ar1, ar2, assume_unique=False)

arr1= [ 0, 10, 20, 40, 60, 80]
arr2 = [10, 30, 40, 50, 70]
diff=np.setdiff1d(arr1,arr2, assume_unique=False)
print('Unique values in array1 that are not in array2:', diff)

Unique values in array1 that are not in array2: [ 0 20 60 80]


In [52]:
# create two 2d arrays
#need to understand this???

ar1 = np.array([[1, 2, 3],
                [4, 4, 1]])
ar2 = np.array([[3, 4, 3],
                [5, 6, 7]])
# set difference ar1 - ar2
ar1_2_diff = np.setdiff1d(ar1, ar2)
# display the array
print(ar1_2_diff)

[1 2]


17. Write a NumPy program to find the set exclusive-or of two arrays. Set exclusive-or will return the sorted, unique values that are in only one (not both) of the input arrays.

Array1:  [ 0 10 20 40 60 80]                                           
Array2:  [10, 30, 40, 50, 70]                                          
Unique values that are in only one (not both) of the input arrays:     
[ 0 20 30 50 60 70 80]

![python-numpy-image-exercise-21.png](attachment:python-numpy-image-exercise-21.png)

In [99]:
#numpy.setxor1d() function find the set exclusive-or of two arrays and 
#return the sorted, unique values that are in only one (not both) of 
#the input arrays.
#Syntax : numpy.setxor1d(arr1, arr2, assume_unique = False)

#Parameters :
#arr1, arr2 : [array_like] Input arrays.
#assume_unique : [bool] If True, the input arrays are both assumed to be 
#unique, which can speed up the calculation. Default is False.

#Return : [ndarray] Sorted 1D array of unique values that are in only one of the input arrays.

array1 = np.array([0, 10, 20, 40, 60, 80])
print("Array1: ",array1)
array2 = [10, 30, 40, 50, 70]
print("Array2: ",array2)
print("Unique values that are in only one (not both) of the input arrays:")
print(np.setxor1d(array1, array2))

Array1:  [ 0 10 20 40 60 80]
Array2:  [10, 30, 40, 50, 70]
Unique values that are in only one (not both) of the input arrays:
[ 0 20 30 50 60 70 80]


18. Write a NumPy program to find the union of two arrays. Union will return the unique, sorted array of values that are in either of the two input arrays.

Array1:  [ 0 10 20 40 60 80]                                           
Array2:  [10, 30, 40, 50, 70]                                          
Unique sorted array of values that are in either of the two input array
s:                                                                     
[ 0 10 20 30 40 50 60 70 80]

![python-numpy-image-exercise-22.png](attachment:python-numpy-image-exercise-22.png)

In [101]:
array1 = np.array([0, 10, 20, 40, 60, 80])
print("Array1: ",array1)
array2 = [10, 30, 40, 50, 70]
print("Array2: ",array2)
print("Unique sorted array of values in either of the two input arrays:")
print(np.union1d(array1, array2))

Array1:  [ 0 10 20 40 60 80]
Array2:  [10, 30, 40, 50, 70]
Unique sorted array of values in either of the two input arrays:
[ 0 10 20 30 40 50 60 70 80]


19. Write a NumPy program to test whether all elements in an array evaluate to True.
Note: 0 evaluates to False in python.

![python-numpy-image-exercise-23.png](attachment:python-numpy-image-exercise-23.png)

In [102]:
#confused on this one
print(np.all([[True,False],[True,True]]))
print(np.all([[True,True],[True,True]]))
print(np.all([10, 20, 0, -50]))
print(np.all([10, 20, -50]))

False
True
False
True


20. Write a NumPy program to find the indices of the maximum and minimum values along the given axis of an array.

Original array:  [1 2 3 4 5 6]                                         
Maximum Values:  5                                                     
Minimum Values:  0

![python-numpy-image-exercise-27.png](attachment:python-numpy-image-exercise-27.png)

In [103]:
x = np.array([1, 2, 3, 4, 5, 6])
print("Original array: ",x)
print("Maximum Values: ",np.argmax(x))
print("Minimum Values: ",np.argmin(x))

Original array:  [1 2 3 4 5 6]
Maximum Values:  5
Minimum Values:  0


21. Write a NumPy program to get the values and indices of the elements that are bigger than 10 in a given array.

![python-numpy-image-exercise-31.png](attachment:python-numpy-image-exercise-31.png)

In [104]:
x = np.array([[0, 10, 20], [20, 30, 40]])
print("Original array: ")
print(x)
print("Values bigger than 10 =", x[x>10])
print("Their indices are ", np.nonzero(x > 10))

Original array: 
[[ 0 10 20]
 [20 30 40]]
Values bigger than 10 = [20 20 30 40]
Their indices are  (array([0, 1, 1, 1], dtype=int64), array([2, 0, 1, 2], dtype=int64))


22. Write a NumPy program to create an array of ones of size 2 and an array of zeros of size 2.

In [105]:
#didn't find this online to double check my work
ones_array=np.ones(2)
zeros_array=np.zeros(2)
print(ones_array)
print(zeros_array)

[1. 1.]
[0. 0.]


23. Write a NumPy program to create a contiguous flattened array.

Original array:                                                        
[[10 20 30]                                                            
 [20 40 50]]                                                           
New flattened array:                                                   
[10 20 30 20 40 50] 

![python-numpy-image-exercise-36.png](attachment:python-numpy-image-exercise-36.png)

In [106]:
x = np.array([[10, 20, 30], [20, 40, 50]])
print("Original array:")
print(x)
y = np.ravel(x) #decreases dimensions down to 1?
print("New flattened array:")
print(y)

Original array:
[[10 20 30]
 [20 40 50]]
New flattened array:
[10 20 30 20 40 50]


24. Write a NumPy program to create a new shape to an array without changing its data.

Reshape 3x2:                                                           
[[1 2]                                                                 
 [3 4]                                                                 
 [5 6]]                                                                
Reshape 2x3:                                                           
[[1 2 3]                                                               
 [4 5 6]] 

![python-numpy-image-exercise-38.png](attachment:python-numpy-image-exercise-38.png)

In [107]:
x = np.array([1, 2, 3, 4, 5, 6])
y = np.reshape(x,(3,2)) 
print("Reshape 3x2:")
print(y)
z = np.reshape(x,(2,3))
print("Reshape 2x3:")
print(z)

Reshape 3x2:
[[1 2]
 [3 4]
 [5 6]]
Reshape 2x3:
[[1 2 3]
 [4 5 6]]


25. Write a NumPy program to change the data type of an array.

[[ 2  4  6]                                                            
 [ 6  8 10]]                                                           
Data type of the array x is: int32                                     
New Type:  float64                                                     
[[  2.   4.   6.]                                                      
 [  6.   8.  10.]]

In [108]:
x = np.array([[2, 4, 6], [6, 8, 10]], np.int32)
print(x)
print("Data type of the array x is:",x.dtype)#dtype is int32 because we me it that way. What's the advantage
# Change the data type of x
y = x.astype(float) #returns new dataframe
print("New Type: ",y.dtype)
print(y)

[[ 2  4  6]
 [ 6  8 10]]
Data type of the array x is: int32
New Type:  float64
[[ 2.  4.  6.]
 [ 6.  8. 10.]]


26. Write a NumPy program to create a 1-D array of 20 element spaced evenly on a log scale between 2. and 5., exclusive.

In [109]:
x =  np.logspace(2., 5., 20, endpoint=False)
print(x)

[  100.           141.25375446   199.5262315    281.83829313
   398.10717055   562.34132519   794.32823472  1122.0184543
  1584.89319246  2238.72113857  3162.27766017  4466.83592151
  6309.5734448   8912.50938134 12589.25411794 17782.79410039
 25118.8643151  35481.33892336 50118.72336273 70794.57843841]


27. Write a NumPy program to concatenate two 2-dimensional arrays.
Sample arrays: ([[0, 1, 3], [5, 7, 9]], [[0, 2, 4], [6, 8, 10]]

[[ 0  1  3  0  2  4]                                                   
 [ 5  7  9  6  8 10]] 

![python-numpy-image-exercise-58.png](attachment:python-numpy-image-exercise-58.png)

In [110]:
a = np.array([[0, 1, 3], [5, 7, 9]])
b = np.array([[0, 2, 4], [6, 8, 10]])
c = np.concatenate((a, b), 1) #what does the one signify here
print(c)

[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


28. Write a Python program to split an array of 14 elements into 3 arrays, each of which has 2, 4, and 8 elements in the original order.
Sample array: [ 1 2 3 4 5 6 7 8 9 10 11 12 13 14]

Original array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]            
After splitting:                                                       
[array([1, 2]), array([3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12, 13,
 14])] 

![python-numpy-image-exercise-61.png](attachment:python-numpy-image-exercise-61.png)

In [111]:
x = np.arange(1, 15)
print("Original array:",x)
print("After splitting:")
print(np.split(x, [2, 6]))

Original array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
After splitting:
[array([1, 2]), array([3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12, 13, 14])]


29. Write a NumPy program to split of an array of shape 4x4 it into two arrays along the second axis.
Sample array :
[[ 0 1 2 3]
[ 4 5 6 7]
[ 8 9 10 11]
[12 13 14 15]]


After splitting horizontally:
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]]), array([], shape=(4, 0), dtype=int64)] 

![python-numpy-image-exercise-62.png](attachment:python-numpy-image-exercise-62.png)

In [112]:
x = np.arange(16).reshape((4, 4))
print("Original array:",x)
print("After splitting horizontally:")
print(np.hsplit(x, [2, 6])) #2 refers to the column split, can't find significance for 6

Original array: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
After splitting horizontally:
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]]), array([], shape=(4, 0), dtype=int32)]


30. Write a NumPy program to get the number of nonzero elements in an array.
Original array:                                                        
[[ 0 10 20]                                                            
 [20 30 40]]                                                           
Number of non zero elements in the above array:                        
5 

![python-numpy-image-exercise-63.png](attachment:python-numpy-image-exercise-63.png)

In [113]:
x = np.array([[0, 10, 20], [20, 30, 40]])
print("Original array:")
print(x)
print("Number of non zero elements in the above array:")
print(np.count_nonzero(x))#only num not included is 0

Original array:
[[ 0 10 20]
 [20 30 40]]
Number of non zero elements in the above array:
5


31. Write a NumPy program to add an extra column to a NumPy array.

![python-numpy-image-exercise-86.png](attachment:python-numpy-image-exercise-86.png)

In [114]:
x = np.array([[10,20,30], [40,50,60]])
y = np.array([[100], [200]])
print(np.append(x, y, axis=1))

[[ 10  20  30 100]
 [ 40  50  60 200]]


32. Write a NumPy program to remove the negative values in a NumPy array with 0.

![python-numpy-image-exercise-90.png](attachment:python-numpy-image-exercise-90.png)

In [115]:
x = np.array([-1, -4, 0, 2, 3, 4, 5, -6])
print("Original array:")
print(x)
print("Replace the negative values of the said array with 0:")
x[x < 0] = 0
print(x)

Original array:
[-1 -4  0  2  3  4  5 -6]
Replace the negative values of the said array with 0:
[0 0 0 2 3 4 5 0]


33. Write a NumPy program to remove all rows in a NumPy array that contain non-numeric values.

![python-numpy-image-exercise-91.png](attachment:python-numpy-image-exercise-91.png)

In [119]:
x = np.array([[1,2,3], [4,5,np.nan], [7,8,9], [True, False, True]])#.nan is the specific function
print("Original array:")
print(x)
print("Remove all non-numeric elements of the said array")
print(x[~np.isnan(x).any(axis=1)]) #removed entire row

Original array:
[[ 1.  2.  3.]
 [ 4.  5. nan]
 [ 7.  8.  9.]
 [ 1.  0.  1.]]
Remove all non-numeric elements of the said array
[[1. 2. 3.]
 [7. 8. 9.]
 [1. 0. 1.]]


34. Write a NumPy program to select indices satisfying multiple conditions in a NumPy array.

Sample array:
a = np.array([97, 101, 105, 111, 117])
b = np.array(['a','e','i','o','u'])

Note: Select the elements from the second array corresponding to elements in the first array that are greater than 100 and less than 110

![python-numpy-image-exercise-92.png](attachment:python-numpy-image-exercise-92.png)

In [120]:
a = np.array([97, 101, 105, 111, 117])
b = np.array(['a','e','i','o','u'])
print("Original arrays")
print(a)
print(b)
print("Elements from the second array  corresponding to elements in the first array  that are greater than 100 and less than 110:")
print(b[(100 < a) & (a < 110)])

Original arrays
[ 97 101 105 111 117]
['a' 'e' 'i' 'o' 'u']
Elements from the second array  corresponding to elements in the first array  that are greater than 100 and less than 110:
['e' 'i']


35. Write a NumPy program to count the frequency of unique values in numpy array.

Original array:                                                        
[10 10 20 10 20 20 20 30 30 50 40 40]                                  
Frequency of unique values of the said array:                          
[[10 20 30 40 50]                                                      
 [ 3  4  2  2  1]]

![python-numpy-image-exercise-94.png](attachment:python-numpy-image-exercise-94.png)

In [121]:
a = np.array( [10,10,20,10,20,20,20,30, 30,50,40,40] )
print("Original array:")
print(a)
unique_elements, counts_elements = np.unique(a, return_counts=True)
print("Frequency of unique values of the said array:")
print(np.asarray((unique_elements, counts_elements)))

Original array:
[10 10 20 10 20 20 20 30 30 50 40 40]
Frequency of unique values of the said array:
[[10 20 30 40 50]
 [ 3  4  2  2  1]]


36. Write a NumPy program to access last two columns of a multidimensional columns.

[[1 2 3]
 [4 5 6]
 [7 8 9]]
 
[[2 3]
 [5 6]
 [8 9]]

![python-numpy-image-exercise-104.svg](attachment:python-numpy-image-exercise-104.svg)

In [122]:
arra = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arra)
result = arra[:,[1,2]]
print(result)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]
 [8 9]]


37. Write a NumPy program to find indices of elements equal to zero in a NumPy array.

Original array:
[1 0 2 0 3 0 4 5 6 7 8]

Indices of elements equal to zero of the said array:
[1 3 5]

![python-numpy-image-exercise-115.svg](attachment:python-numpy-image-exercise-115.svg)

In [123]:
nums = np.array([1,0,2,0,3,0,4,5,6,7,8])
print("Original array:")
print(nums)
print("Indices of elements equal to zero of the said array:")
result = np.where(nums == 0)[0]
print(result)

Original array:
[1 0 2 0 3 0 4 5 6 7 8]
Indices of elements equal to zero of the said array:
[1 3 5]
